# Generated by Django 4.0.4 on 2024-10-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(help_text='Enter sizes seperates by commas, e.g S,M,L', max_length=100),
        ),
    ]
