# Generated by Django 5.1.2 on 2024-11-04 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Image1',
            new_name='Image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Image2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Image3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Image4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
